# Nome do workflow que aparecerá na aba "Actions" do GitHub
name: CI do Frontend Next.js

# Define quando este workflow será acionado
on:
  push:
    branches:
      - main # Em pushes para o branch 'main'
      - develop # E para o branch 'develop' (se você usar)
    # Se estiver em um MONOREPO e esta CI for para a pasta 'frontend/',
    # você pode adicionar um filtro de caminho para rodar apenas quando arquivos do frontend mudarem:
    # paths:
    #   - 'frontend/**'
    #   - '.github/workflows/frontend-ci.yml' # Ou se o próprio workflow mudar
  pull_request:
    branches:
      - main # Em PRs direcionados ao 'main'
      - develop # E para PRs direcionados ao 'develop'
    # Se estiver em um MONOREPO:
    # paths:
    #   - 'frontend/**'
    #   - '.github/workflows/frontend-ci.yml'

jobs:
  build_and_test_frontend:
    name: Construir e Testar Aplicação Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 1. Baixar o código (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js versão ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 3. Instalar Dependências
        run: npm ci

      - name: 4. Rodar Testes Unitários/Integração (Jest)
        run: npm test

      - name: 5. Construir Projeto (Build)
        run: npm run build
          ${{ secrets.STAGING_API_URL }}
