# .github/workflows/frontend-ci.yml

name: CI do Frontend Next.js

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_and_test_frontend:
    name: Construir e Testar Aplicação Frontend
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: 1. Baixar o código (Checkout)
        uses: actions/checkout@v4

      - name: 2. Configurar Node.js versão ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: 3. Instalar Dependências
        run: npm ci

      - name: 4. Rodar Testes Unitários/Integração (Jest)
        run: npm test

      - name: 5. Construir Projeto (Build)
        run: npm run build